hostPort: connect:9102
lowercaseOutputName: true
lowercaseOutputLabelNames: true

rules:
  - pattern: 'kafka.connect<type=connector-task-metrics, connector="([^"]+)", task="([^"]+)"><>([^:]+)'
    name: kafka_connect_$3
    labels:
      connector: "$1"
      task: "$2"
    type: GAUGE
  - pattern: 'kafka.connect<type=connect-worker-metrics><>([^:]+)'
    name: kafka_connect_worker_$1
    type: GAUGE
  - pattern: 'kafka.connect<type=connect-metrics><>([^:]+)'
    name: kafka_connect_$1
    type: GAUGE
  - pattern: 'kafka.producer<type=producer-metrics, client-id="([^"]+)"><>([^:]+)'
    name: kafka_connect_producer_$2
    labels:
      client_id: "$1"
    type: GAUGE
  - pattern: 'kafka.consumer<type=consumer-metrics, client-id="([^"]+)"><>([^:]+)'
    name: kafka_connect_consumer_$2
    labels:
      client_id: "$1"
    type: GAUGE
